### PR TITLE
Issue#37: Documentation for fully qualified class names

### LINKED ISSUE #35: Unknown Properties for Options
Hi,

I am trying to get the output of the minification to be a single file (one for js and another for css). I was experimenting with the options to get this to work and get the following errors where the type cannot be resolved: 

```
task additionalJsMinify(type: org.gradlewebtools.minify.JsMinifyTask) {
    srcDir = project.file(myJsPath)
    dstDir = project.file(myJsPath)
    options.ignoreMinFiles = false
    options.angularPass = false
    options.compilationLevel = CompilationLevel.SIMPLE_OPTIMIZATIONS
}
```

`Could not get unknown property 'CompilationLevel' for task ':additionalJsMinify' of type org.gradlewebtools.minify.JsMinifyTask.`

```
task myCssMinify(type: org.gradlewebtools.minify.CssMinifyTask) {
    srcDir = project.file(myCssPath)
    dstDir = project.file(myCssPath)
    options.outputFormat = OutputFormat.COMPRESSED
}
```

`Could not get unknown property 'OutputFormat' for task ':myCssMinify' of type org.gradlewebtools.minify.CssMinifyTask.`

Am I missing an import or a namespace prefix?

Also, is it possible to specify a list of source files instead of a srcDir? I'd like to ensure the minification is done in a specific order.

I have this as the dependency:

```
plugins {
    id("org.gradlewebtools.minify") version "1.3.0"
}
```

Thanks.

### LINKED ISSUE #37: Consider using custom types to configure minify backends
https://github.com/gradle-webtools/gradle-minify-plugin/issues/35#issuecomment-1073812646

### PR DESCRIPTION
**Pull request by 616slayer616**
I think this covers the documentation.
But using custom typed would look better so we should enable that for the future.

I would like to release 2.0 some time with the new closure compiler: But I was hoping we could do something for the groovy users before

### CODE REVIEW

**Review by timon-schelling — COMMENTED** [review]
Maybe add a Message in the config table that explains the usage of external types?

**Comment by timon-schelling** [comment]
while you are at it, maybe you could also add type names in the table?

**Comment by 616slayer616** [comment]
> while you are at it, maybe you could also add type names in the table?

Oh yes good idea!

The table is going to be huge though😂

**Comment by 616slayer616** [comment]
@timon-schelling 
What I'm not sure about:
does charset also have to be fully qualified?

**Comment by timon-schelling** [comment]
What charset?

**Comment by 616slayer616** [comment]
The option
Bildschirmfoto 2022-03-21 um 15 12 47

**Comment by timon-schelling** [comment]
> The option Bildschirmfoto 2022-03-21 um 15 12 47

I guess... never tried that tho

**Comment by 616slayer616** [comment]
@timon-schelling I think we can merge this and create a release right?

**Pull request merged**
